Avoid Forced Reflow when no input elements present on page.
autoNumeric/autoNumeric pull request #731
Opened 2022-01-17 18:07 UTC by gmhawash

Wrapped _historyTableAdd call inside a window.requestAnimationFrame() to avoid Forced Reflow

requestAnimationFrame is used to schedule this between animation frame painting to avoid
"Forced reflow while executing JavaScript" violation which is expensive when there are a huge number of
elements (currency) to format. The forced reflow is caused by calling window.getSelection() in AutoNumericHelper/getElementSelection() and then accessing the resulting selection variable in any way
(in this case. selection.getRangeAt(0)).

2022-03-17 23:48 UTC, melloware approved these changes

2023-02-13 20:08 UTC, AlexandreBonneau requested changes

2023-02-13 20:08 UTC, AlexandreBonneau commented on package.json
> +    "prepare": "yarn build",
Please do not add unnecessary scripts to the package.json file

2023-02-13 20:08 UTC, AlexandreBonneau commented on src/AutoNumeric.js
> -                // Save in the history the last known raw value and formatted result selection
Please keep the original comment before the completed one you added

2023-02-13 20:08 UTC, AlexandreBonneau commented on src/AutoNumeric.js
> +                window.requestAnimationFrame(() => {this._historyTableAdd(); });
No need to add the `{` and `}` characters here.

```
window.requestAnimationFrame(() => this._historyTableAdd());
```
should be ok

2023-04-04 10:47 UTC, AlexandreBonneau commented
This is fixed in `4.8.2`

2023-04-04 10:47 UTC, closed without merging